
[maxdurability]
	#The durability the gun starts with and the max it can repair to
	maxdurability = 2000.0

[gunsbreak]
	#Do guns break or not
	gunsbreak = false

[jamchance]
	#Set to zero to stop jamming entirely
	jamchance = 20.0

[shotgunlist]
	#Add any shotguns here to prevent the bug where they take 10 times more durability
	shotgunlist = ["tacz:aa12", "tacz:db_short", "tacz:db_long"]

